sudo: required
services:
  - docker
before_install:
  - docker build -t ajaypati/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run ajaypati/react-test npm test -- --coverage
after_success:
  - docker build -t ajaypati/multi-client ./client
  - docker build -t ajaypati/multi-nginx ./nginx
  - docker build -t ajaypati/multi-server ./server
  - docker build -t ajaypati/multi-worker ./worker
  # login to docker CLI and push this images to dockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajaypati/multi-client
  - docker push ajaypati/multi-nginx
  - docker push ajaypati/multi-server
  - docker push ajaypati/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-703745605407"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"